export let fakeUsers = [
    { id: 1, name: 'Amir Benaouda', dob: '11/23/1985', from: 'Oran', to: 'Toulouse', date: 'September 5th', updated: '3 mins ago' },
    { id: 2, name: 'Léa Dupont', dob: '05/16/1992', from: 'Bordeaux', to: 'Annaba', date: 'September 6th', updated: '5 mins ago' },
    { id: 3, name: 'Karim Boudiaf', dob: '08/02/1988', from: 'Algiers', to: 'Lyon', date: 'September 7th', updated: '10 mins ago' },
    { id: 4, name: 'Camille Leclerc', dob: '03/29/1997', from: 'Marseille', to: 'Béjaïa', date: 'September 8th', updated: '15 mins ago' },
    { id: 5, name: 'Riad Bouteflika', dob: '12/07/1981', from: 'Constantine', to: 'Nice', date: 'September 9th', updated: '20 mins ago' },
    { id: 6, name: 'Chloé Mercier', dob: '09/14/1990', from: 'Toulouse', to: 'Oran', date: 'September 10th', updated: '25 mins ago' },
    { id: 7, name: 'Sofiane Lahlou', dob: '04/22/1995', from: 'Tizi Ouzou', to: 'Paris', date: 'September 11th', updated: '30 mins ago' },
    { id: 8, name: 'Céline Moreau', dob: '07/05/1983', from: 'Lille', to: 'Sétif', date: 'September 12th', updated: '35 mins ago' },
    { id: 9, name: 'Sabrina Djermoune', dob: '11/18/1989', from: 'Skikda', to: 'Montpellier', date: 'October 6th', updated: '1 hour ago' },
    { id: 10, name: 'Maxime Renard', dob: '06/30/1994', from: 'Strasbourg', to: 'Tlemcen', date: 'October 7th', updated: '1 hour ago' },
    { id: 11, name: 'Farid Zidane', dob: '02/09/1986', from: 'Mascara', to: 'Grenoble', date: 'October 8th', updated: '1 hour ago' },
    { id: 12, name: 'Manon Gauthier', dob: '10/12/1991', from: 'Rennes', to: 'Sidi Bel Abbès', date: 'October 9th', updated: '1 hour ago' },
    { id: 13, name: 'Rafik Bouteflika', dob: '03/25/1993', from: 'Mostaganem', to: 'Nantes', date: 'October 10th', updated: '1 hour ago' },
    { id: 14, name: 'Inès Lambert', dob: '08/07/1996', from: 'Dijon', to: 'Boumerdès', date: 'October 11th', updated: '1 hour ago' },
    { id: 15, name: 'Kamel Zidane', dob: '01/14/1984', from: 'Msila', to: 'Toulon', date: 'October 12th', updated: '1 hour ago' },
    { id: 16, name: 'Juliette Durand', dob: '11/29/1998', from: 'Valenciennes', to: 'Béchar', date: 'October 13th', updated: '1 hour ago' },
    { id: 17, name: 'Tarek Bouzid', dob: '07/11/1990', from: 'Bordj Bou Arreridj', to: 'Caen', date: 'October 14th', updated: '1 hour ago' },
    { id: 18, name: 'Charlotte Perrin', dob: '04/03/1985', from: 'Amiens', to: 'Djelfa', date: 'October 15th', updated: '1 hour ago' },
    { id: 19, name: 'Sofiane Chikhi', dob: '09/20/1992', from: 'Khenchela', to: 'Reims', date: 'September 14th', updated: '45 mins ago' },
    { id: 20, name: 'Océane Roy', dob: '06/12/1987', from: 'Le Havre', to: 'Biskra', date: 'September 15th', updated: '50 mins ago' },
    { id: 21, name: 'Rayan Belmadi', dob: '02/27/1995', from: 'El Bayadh', to: 'Rouen', date: 'September 16th', updated: '55 mins ago' },
    { id: 22, name: 'Léa Durand', dob: '11/08/1999', from: 'Nancy', to: 'Tébessa', date: 'September 17th', updated: '1 hour ago' },
    { id: 23, name: 'Karim Boualem', dob: '08/14/1982', from: 'El Oued', to: 'Orléans', date: 'September 18th', updated: '1 hour ago' },
    { id: 24, name: 'Chloé Petit', dob: '05/02/1991', from: 'Bordeaux', to: 'Bouira', date: 'September 19th', updated: '1 hour ago' },
    { id: 25, name: 'Sofiane Bennacer', dob: '03/29/1988', from: 'Tamanrasset', to: 'Metz', date: 'September 20th', updated: '1 hour ago' },
    { id: 26, name: 'Manon Girard', dob: '12/16/1997', from: 'Tours', to: 'Médéa', date: 'September 21st', updated: '1 hour ago' },
    { id: 27, name: 'Riad Benyahia', dob: '09/07/1983', from: 'Naâma', to: 'Dijon', date: 'September 22nd', updated: '1 hour ago' },
    { id: 28, name: 'Léa Deschamps', dob: '04/11/1994', from: 'Angers', to: 'Souk Ahras', date: 'September 23rd', updated: '1 hour ago' },
    { id: 29, name: 'Tarek Zemmouri', dob: '07/23/1989', from: 'Tipaza', to: 'Besançon', date: 'September 24th', updated: '1 hour ago' },
    { id: 30, name: 'Camille Lefebvre', dob: '02/05/1996', from: 'Le Mans', to: 'Ouargla', date: 'September 25th', updated: '1 hour ago' },
    { id: 31, name: 'Amelia Brown', dob: '10/10/1990', from: 'Bordeaux', to: 'Nice', date: 'September 26th', updated: '1 hour ago' },
    { id: 32, name: 'Lucas Taylor', dob: '11/11/1995', from: 'Toulouse', to: 'Lyon', date: 'September 27th', updated: '1 hour ago' },
    { id: 33, name: 'Grace Anderson', dob: '12/12/1989', from: 'Oran', to: 'Algiers', date: 'September 28th', updated: '1 hour ago' },
    { id: 34, name: 'Henry Martinez', dob: '01/01/1994', from: 'Nice', to: 'Bordeaux', date: 'September 29th', updated: '1 hour ago' },
    { id: 35, name: 'Luna Thomas', dob: '02/02/1988', from: 'Marseille', to: 'Paris', date: 'September 30th', updated: '1 hour ago' },
    { id: 36, name: 'Leo Davis', dob: '03/03/1993', from: 'Toulouse', to: 'Lyon', date: 'October 1st', updated: '1 hour ago' },
    { id: 37, name: 'Chloe Johnson', dob: '04/04/1987', from: 'Oran', to: 'Algiers', date: 'October 2nd', updated: '1 hour ago' },
    { id: 38, name: 'Mason Wilson', dob: '05/05/1992', from: 'Nice', to: 'Bordeaux', date: 'October 3rd', updated: '1 hour ago' },
    { id: 39, name: 'Lily Taylor', dob: '06/06/1988', from: 'Marseille', to: 'Paris', date: 'October 4th', updated: '1 hour ago' },
    { id: 40, name: 'Elijah Anderson', dob: '07/07/1993', from: 'Toulouse', to: 'Lyon', date: 'October 5th', updated: '1 hour ago' }
 ];